#! /bin/sh

# Autostart
sxhkd &
xrandr --rate 144 &
xrdb -load $HOME/.config/.Xresources &
setxkbmap -option caps:escape &
pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &
feh --bg-fill --randomize $HOME/Wallpapers/* &
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D 
$HOME/.config/polybar/launch.sh &
# Start 
setxkbmap -layout us,ar -option grp:alt_shift_toggle
setxkbmap -option 'grp:alt_shift_toggle' -layout us,ar -variant ,qwerty
# Workspaces
# Monitors

if [[ $(xrandr --query | grep 'HDMI-1 connected') ]]; then
  xrandr --output HDMI-1 --auto --left-of eDP-1
  bspc monitor HDMI-1 -d 1 2 3
  bspc monitor eDP-1 -d 4 5 6
else
  bspc monitor -d 1 2 3 4 5 6
fi
# End Monitors
# Other stuff
bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.618
bspc config top_padding          27
bspc config bottom_padding       0
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Start Rules
# Cloring
bspc config normal_border_color "#fff"
bspc config focused_border_color "#fff"

bspc rule -a Google-chrome desktop='^1'
bspc rule -a Firefox-Developer-Edition desktop='^1'
bspc rule -a Terminator desktop='^2'
bspc rule -a Alacritty desktop='^2'
bspc rule -a jetbrains-phpstorm='^2'
bspc rule -a Code desktop='^2'
bspc rule -a VSCodium desktop='^2'
bspc rule -a jetbrains-idea desktop='^2'
bspc rule -a jetbrains-pycharm-ce desktop='^2'
bspc rule -a Org.gnome.Nautilus desktop='^3'
bspc rule -a Gedit desktop='^3'
bspc rule -a postman desktop='^4'
bspc rule -a Slack desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a "GitHub Desktop" desktop='^4'
bspc rule -a telegram desktop='^5'
bspc rule -a vlc desktop='^5'

